name:  RssGenerator
author:  cleverscript
current:  v.0.0.1
category:  Components
tags:  [rss,generator,goomla]
docs:  http://cleverscript.ru/index.php/cms/joomla
demo:  http://cleverscript.ru/index.php?option=com_rssgenerator&view=rssgenerator